name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build C Code
      run: |
         cc main.c mongoose.c -D MG_ARCH=MG_ARCH_UNIX  
    - name: install deps
      run: | 
        sudo apt -y update
        sudo apt -y install build-essential make gcc-arm-none-eabi stlink-tools git cmake gcc-riscv64-unknown-elf
    - name: Build
      run: |
        cd examples/http-server
        make
